### PR TITLE
Add Non-Linear Damping

### PR DESCRIPTION
**Pull request by andermi**
Use `PCBiasCurrCommand` service to set winding current `bias` for additional torque damping towards piston extents

Requires https://github.com/osrf/buoy_msgs/pull/13

### CODE REVIEW

**Comment by andermi** [comment]
checks will fail until https://github.com/osrf/buoy_msgs/pull/13 is merged

edit: I guess not, since it's just python (no compilation)

**Comment by chapulina** [comment]
> checks will fail until https://github.com/osrf/buoy_msgs/pull/13 is merged
> edit: I guess not, since it's just python (no compilation)

Yeah we could add some tests that actually run the python scripts to make sure they're working

**Comment by chapulina** [comment]
@andermi , how do you recommend I test this PR?

**Comment by andermi** [comment]
Good question. I think we could set the config file for the bias node to something reasonable, move the piston back and forth at some velocity and check that the bias and resulting counteractive damping force is applied.

**Comment by andermi** [comment]
I have some updates to apply from testing it on the physical buoy.

**Comment by andermi** [comment]
will actually fail until https://github.com/osrf/buoy_msgs/pull/13 due to packrate param function

**Comment by chapulina** [comment]
I'm trying to test this against the sim, but I'm not sure that should work yet? I'm trying:

```
ros2 launch buoy_gazebo mbari_wec.launch.py
```

Then

```
ros2 launch buoy_examples torque_controller_cpp.launch.py
```

But it fails to find all the services. I'm not sure if those should already be available.

**Comment by chapulina** [comment]
> I'm not sure that should work yet?

Ok, I figured it out, we need the no-op controller from https://github.com/osrf/buoy_sim/pull/68 to provide the missing services!

**Review by chapulina — APPROVED** [review]

**Comment by andermi** [comment]
> we need the no-op controller

Sorry, I should have listed that :man_facepalming:

**Pull request merged**
