### PR TITLE
Better api

### PR DESCRIPTION
**Pull request by andermi**
haven't started on readme yet...

design (this version untested with real buoy):
- include/buoy_examples/controller.hpp (if we keep this idea, probably don't want it to be in the "examples" package):
-- templated base class exposing all interfaces (services/subscribers) to the buoy
-- utilizes CRTP static_cast to user-derived controller to use user callback for data subscribers
- include/buoy_examples/torque_controller.hpp
-- declare user-derived controller with CRTP to base class
-- declare use of control policy member
-- declare user-defined power_callback and set_params
- src/torque_controller.cpp
-- main, controller configuration, and definition of callback
- include/buoy_examples/torque_control_policy.hpp
-- define control policy (conversion from motor rpm->winding current)
-- define set_params to load params for policy

python gain_scheduler_node.py & damping_selector.py have not been tested yet

### CODE REVIEW

**Comment by chapulina** [comment]
I changed the base branch for this PR from `main` to the branch on #2 , so this PR only shows the diff from the other PR.

**Comment by chapulina** [comment]
> include/buoy_examples/controller.hpp (if we keep this idea, probably don't want it to be in the "examples" package):

One thing to consider is whether this base class is required to control the buoy, or recommended but not required, or just one example for how it could be done. Depending on the answer, we may want to create a new "controller base" package. 

I could also see that header living within the `buoy_msgs` package itself too. A parallel would be how the [sensor_msgs](https://github.com/ros2/common_interfaces/tree/master/sensor_msgs) package provides not only the messages, but also [convenient C++ APIs for working with those messages](https://github.com/ros2/common_interfaces/tree/master/sensor_msgs/include/sensor_msgs).

**Comment by chapulina** [comment]
@andermi , let me know if you'd like help fixing conflicts and linters in this PR. Just making sure we don't duplicate work 😄

**Comment by andermi** [comment]
@chapulina , ~~how do you get the linter to ignore `using namespace std::chrono_literals;` ? Also, is there a clever way to apply the uncrustify patch?~~
got it

**Comment by andermi** [comment]
`colcon test` passes:  

```
Label Time Summary:  
copyright     =   0.67 sec*proc (1 test)  
cppcheck      =   0.21 sec*proc (1 test)  
cpplint       =   0.34 sec*proc (1 test)  
flake8        =   0.26 sec*proc (1 test)  
lint_cmake    =   0.18 sec*proc (1 test)  
linter        =   2.53 sec*proc (8 tests)  
pep257        =   0.21 sec*proc (1 test)  
uncrustify    =   0.21 sec*proc (1 test)  
xmllint       =   0.46 sec*proc (1 test)
```

**Review by hamilton8415 — APPROVED** [review]

**Pull request merged**
